### ISSUE TITLE
how to fix error when upload file or image

### ISSUE THREAD

**Issue by khonyuen** [sahilr2050/yii2-redactor-s3#1]
{"name":"Exception","message":"Class 'backend\\components\\aws\\S3' not found","code":0,"type":"Error","file":"C:\\laragon\\www\\mukpr\\vendor\\sahilr2050\\yii2-redactor-s3\\models\\FileUploadModel.php","line":36,"stack-trace":["#0 C:\\laragon\\www\\mukpr\\vendor\\sahilr2050\\yii2-redactor-s3\\actions\\ImageUploadAction.php(24): Sahilr2050\\redactor\\models\\FileUploadModel->upload()","#1 [internal function]: Sahilr2050\\redactor\\actions\\ImageUploadAction->run()","#2 C:\\laragon\\www\\mukpr\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)","#3 C:\\laragon\\www\\mukpr\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)","#4 C:\\laragon\\www\\mukpr\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('image', Array)","#5 C:\\laragon\\www\\mukpr\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('redactor/upload...', Array)","#6 C:\\laragon\\www\\mukpr\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 C:\\laragon\\www\\mukpr\\backend\\web\\index.php(18): yii\\base\\Application->run()","#8 {main}"]}

**Comment by cloudemycomau** [comment]
This is the first line I wrote. 

https://github.com/sahilr2050/yii2-redactor-s3#modifying-for-own-use-do-not-use-this-in-your-project-i-can-make-a-change-according-to-my-needs

However, if you still want to use, then you need to create an S3.php file in the components folder which you need to write a function `uploadSingleFile` with a simple object upload code to S3 using PHP S3 SDK.

Declare the params:
fileUploadUrl: a place where you want to store the image
AWS_EFFECTIVE_URL: a URL of an S3 bucket. Ex: https://{bucketname}.s3.{region}.amazonaws.com/

**Comment by sahilr2050** [comment]
This is the first line I wrote.

https://github.com/sahilr2050/yii2-redactor-s3#modifying-for-own-use-do-not-use-this-in-your-project-i-can-make-a-change-according-to-my-needs

However, if you still want to use, then you need to create an S3.php file in the components folder which you need to write a function uploadSingleFile with a simple object upload code to S3 using PHP S3 SDK.

Declare the params:
fileUploadUrl: a place where you want to store the image
AWS_EFFECTIVE_URL: a URL of an S3 bucket. Ex: https://{bucketname}.s3.{region}.amazonaws.com/
